# Generated by Django 2.1 on 2020-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_status',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
